name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.17.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 60.204.234.117
          username: root
          port: 22
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /www/wwwroot/youmake.fun
            git pull origin main
            npm install
            npm run build
            pm2 start npm --name "youmake-fun" -- run start || pm2 restart youmake-fun 